//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnkoSoftware_Application.EF_EnkoSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRecord
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Street { get; set; }
        public int StreetNo { get; set; }
        public int ZipCode { get; set; }
        public int CityId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual City City { get; set; }
    }
}
